# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7bbdb6f7898d64bf3499495f155117f0a952e6415e6900fa887ddf7240560ba99d07c5f115bb006b0d1dbf0470a1cc5b7bb57ea1eefe21baf820bd7c72de40a

test:
  secret_key_base: d7e713b91007e9789fb790cc0e5d44f12bb70ebf10351632a14204c57229235b20df0d7c3d6f423c2824c9e640a0904bbebb8325a204a2c6db90dd013dcf5bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
